USE ayakkala;

DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Rooms;

CREATE TABLE Rooms(
RoomId CHAR(3) PRIMARY KEY,
roomName VARCHAR(50) NOT NULL,
beds INTEGER,
bedType VARCHAR(50),
maxOccupancy INTEGER,
basePrice DECIMAL(10,2),
decor VARCHAR(50)
);

CREATE TABLE Reservations(
`Code` INTEGER PRIMARY KEY,
Room CHAR(3),
CheckIn DATE,
CheckOut DATE,
Rate DECIMAL(10,3),
LastName VARCHAR(20),
FirstName VARCHAR(20),
Adults INTEGER,
KIDS INTEGER,
FOREIGN KEY (Room) REFERENCES Rooms (RoomId)
);